pipeline {
    agent any

    stages {

        stage('Build Backend') {
            steps {
                script {
                    load 'jenkins/pipeline/buildBackend.groovy'
                }
            }
        }

        stage('Security Scan') {
            steps {
                script {
                    load 'jenkins/pipeline/runTrivy.groovy'
                }
            }
        }

        stage('Deploy Backend') {
            steps {
                script {
                    load 'jenkins/pipeline/deployBackend.groovy'
                }
            }
        }

        stage('Health Check') {
            steps {
                script {
                    load 'jenkins/pipeline/healthCheckBackend.groovy'
                }
            }
        }
    }
}