apiVersion: v1
kind: Service

metadata:
  name: cloudpilot-backend-service
  namespace: cloudpilot

spec:
  selector:
    app: cloudpilot-backend

  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

  type: ClusterIP